define(["jade"],function(jade){

return function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (user) {
buf.push("<div class=\"profilebar\"><h1 class=\"profile_name\"><i class=\"glyphicon glyphicon-chevron-right\"></i>" + (jade.escape(null == (jade_interp = user.get("name")) ? "" : jade_interp)) + "</h1><img" + (jade.attr("src", "" + (user.get('avatar')) + "", true, false)) + "/>\n<div id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\" class=\"panel-group\"><div class=\"panel panel-default\"><div id=\"headingOne\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">プロフィール</a></h4></div><div id=\"collapseOne\" role=\"tabpanel\" aria-labelledby=\"headingOne\" class=\"panel-collapse collapse in\"><ul class=\"list-group\"><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li></ul></div></div><div class=\"panel panel-default\"><div id=\"headingTwo\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\" class=\"collapsed\">各種アカウント</a></h4></div><div id=\"collapseTwo\" role=\"tabpanel\" aria-labelledby=\"headingTwo\" class=\"panel-collapse collapse\"><ul class=\"list-group\"><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li></ul></div></div><div class=\"panel panel-default\"><div id=\"headingThree\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\" class=\"collapsed\">実績</a></h4></div><div id=\"collapseThree\" role=\"tabpanel\" aria-labelledby=\"headingThree\" class=\"panel-collapse collapse\"><div class=\"panel-body\">Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven&apos;t heard of them accusamus labore sustainable VHS.</div></div></div></div></div><div class=\"profilecontent\"></div>");}.call(this,"user" in locals_for_with?locals_for_with.user:typeof user!=="undefined"?user:undefined));;return buf.join("");
};

});
