define(["jade"],function(jade){

return function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (achivement) {
buf.push("<div class=\"optionbar\"><div data-js=\"closePanel\" class=\"close_btn\"><div class=\"glyphicon glyphicon-remove-sign\"></div></div><div class=\"option_title\">Achivement<span>（実績）</span></div></div><div class=\"main\"><div class=\"main_title\"><span class=\"sub\">実績名：</span>\"" + (jade.escape((jade_interp = achivement.get("Name")) == null ? '' : jade_interp)) + "\"<div" + (jade.attr("style", "width: " + (achivement.get('CurrentProgress') * 100) + "%; background-color: rgb(220," + (achivement.get('CurrentProgress')*100+120) + ",0)", true, false)) + " class=\"achive_progress\"></div><div class=\"achive_progress-wrap\"></div></div><div class=\"main_content\"><div class=\"info_panel\"><div class=\"info_title\">達成</div><div class=\"info_content type-pict\"><div class=\"table\"><div class=\"table-cell\"><div class=\"percent\">" + (jade.escape((jade_interp = achivement.get("CurrentProgress")*100) == null ? '' : jade_interp)) + "%</div><div class=\"img_box type-2\"><style type=\"text/css\"><!--\n  .img_box.type-2:after{margin-top: " + (jade.escape((jade_interp = 100 - achivement.get("CurrentProgress")*100) == null ? '' : jade_interp)) + "%;}\n  --></style></div><div class=\"diff\">前日比<div class=\"value\">+" + (jade.escape((jade_interp = achivement.get("ProgressDiff")) == null ? '' : jade_interp)) + "%</div></div></div></div></div></div><div class=\"info_panel\"><div class=\"info_title\">収得条件</div><div class=\"info_content\">" + (jade.escape((jade_interp = achivement.get("Description")) == null ? '' : jade_interp)) + "</div></div><div class=\"info_panel\"><div class=\"info_title\">収得率</div><div class=\"info_content type-pict\"><div class=\"table\"><div class=\"table-cell\"><div class=\"percent\">" + (jade.escape((jade_interp = achivement.get("AwardedRate")*100) == null ? '' : jade_interp)) + "%</div><div class=\"img_box type-1\"><style type=\"text/css\"><!--\n  .img_box.type-1:after{margin-top: " + (jade.escape((jade_interp = 100 - achivement.get("AwardedRate")*100) == null ? '' : jade_interp)) + "%;}\n  --></style></div><div class=\"sum\">収得者数<div class=\"value\">" + (jade.escape((jade_interp = achivement.get("AwardedPerson")) == null ? '' : jade_interp)) + "名<span>/" + (jade.escape((jade_interp = achivement.get("SumPerson")) == null ? '' : jade_interp)) + "名</span></div></div></div></div></div></div><div class=\"info_panel\"><div class=\"info_title\">達成率の推移</div><div class=\"info_content\"><div id=\"AcuireRateGraph\"></div></div></div><div class=\"info_panel\"><div class=\"info_title\">サークルメンバーの状況</div><div class=\"info_content\"></div></div><div class=\"info_panel\"><div class=\"info_title\">習得率の推移</div><div class=\"info_content\"></div></div></div></div>");}.call(this,"achivement" in locals_for_with?locals_for_with.achivement:typeof achivement!=="undefined"?achivement:undefined));;return buf.join("");
};

});
